### PR TITLE
New Blueprint: Grid Variations enabled

### PR DESCRIPTION
**Pull request by bph**
Using this blueprint configuration

- Logs into wp-admin
- Installs Gutenberg plugin and activates it
- enabled the Grid Variations from the Gutenberg > Experiments page
- Navigates to the Site Editor screen as landing page.

### CODE REVIEW

**Comment by adamziel** [comment]
This looks great @bph ! The only thing I'd change is the filename – it should be `blueprint.json`. This way we follow the same naming convention as the WordPress plugins repository AND the automated tools will be able to reliably identify the Blueprint file even for directories with more than one `.json` file.

**Comment by bph** [comment]
🤦‍♀️ oops: It's written right there in the instructions 
>Your Pull Request must contain a single blueprint.json file under a path blueprints/your-blueprint-name/blueprint.json 

should work now.

**Comment by adamziel** [comment]
Thank you so much @bph!

**Comment by adamziel** [comment]
The Gallery page was automatically rebuilt: https://github.com/adamziel/blueprints/blob/trunk/GALLERY.md

**Pull request merged**
