### PR TITLE
Blueprints crash course V2

### PR DESCRIPTION
**Pull request by ironnysh**
Hi @adamziel, I made a few adjustments to the copy and file structure of the course (renamed to _Blueprints 101_).

I hope it's okay.

PS-- I don't have access to your repo, so I made a fork and a PR of your PR #5 :-)

### CODE REVIEW

**Comment by ironnysh** [comment]
Forgot something important: are the shorthands documented somewhere?

**Comment by adamziel** [comment]
This is fantastic @ironnysh, thank you so much! I really like how you condensed the number of pages while keeping the structure clean ❤️ 

> Forgot something important: are the shorthands documented somewhere?

They aren't at the moment, I've added them as an experimental feature a few months ago and didn't want to spread them too much in case I'd have to remove them later on. Today I'm quite certain they're here to stay which also means there are no more blockers to documenting them.

**Comment by ironnysh** [comment]
Thanks, @adamziel, always a pleasure! 😃

> there are no more blockers to documenting them.

Coolio, let's do it. Is there a list somewhere (I can also "extract" these from a typescript file, if you'll point me to it)?

**Comment by adamziel** [comment]
@ironnysh it's here:

https://github.com/WordPress/wordpress-playground/blob/d135cafc10d0e2e624c0ecd47e24b1ac4be4cec0/packages/playground/blueprints/src/lib/compile.ts#L100-L146

For now those are:

* constants (`{"constants": { "const_a": "value", "const_b": "value" } }`)
* siteOptions (`{"siteOptions": { "blogname": "My blog!" } }`)
* plugins  (`{"plugins": [  "gutenberg", { "resource": "url", "url": "..." } ] }`)
* login (`{"login": true}` or `{"login": { "username": "admin", "password": "password" } }`

**Comment by ironnysh** [comment]
Perfect, thanks!

I think the [Steps page](https://wordpress.github.io/wordpress-playground/blueprints-api/steps) would be the natural place for these, right?

I can open a new issue for this on the [main repo](https://github.com/WordPress/wordpress-playground/issues), or is there another process for documentation now?

**Comment by adamziel** [comment]
Sounds great @ironnysh, thank you! A PR for the main repo would be the right way for now until we can figure out a Playground-based workflow.

**Pull request merged**
