### PR TITLE
Blueprints 101 guide

### LINKED ISSUE #2: Blueprints developer documentation
Let's provide developers with ample examples on how to build Blueprints. One outline is proposed in https://github.com/WordPress/blueprints-library/issues/64

### PR DESCRIPTION
**Pull request by adamziel**
## Description

[<kbd> <br>Click here to read the content :-)<br> </kbd>](https://github.com/adamziel/blueprints/blob/blueprints-crash-course/docs/index.md)

Launching this Blueprint community space hinges on good materials to explain what Blueprints are and how developers can work with them.

This PR proposes a few pages to cover:

1. What are Blueprints and how are they useful?
2. How to run Blueprints
3. Building your first Blueprint
4. Debugging Blueprints
5. Developer Tools
6. More Resources

It's a loose interpretation of [the previously proposed outline](https://github.com/WordPress/blueprints-library/issues/64) that covers roughly the same topics in a lean way.

## Reviewing

[<kbd> <br>Preview proposed documentation<br> </kbd>](https://github.com/adamziel/blueprints/blob/blueprints-crash-course/docs/index.md)

cc @flexseth @bph @jonathanbossenger @ironnysh @westnz @justintadlock @annezazu @bgrgicak @brandonpayton @dmsnell for your opinions. I'd love to learn:

1. Do you think this covers enough to launch the Community Space and iterate later?
2. Are these pages clear? Do they do a good job of getting a person from 0 to familiar?
3. What would you change?

## Documentation format

This PR uses Markdown because it's easy to write and can be readily previewed on GitHub.

In parallel, we're exploring [a Playground-based documentation writing workflow](https://github.com/adamziel/playground-docs-workflow). It's not ready for production use yet and I didn't want to block the community space on these explorations. Once it's finished, these docs should be easy to migrate.

Closes https://github.com/adamziel/blueprints/issues/2

### CODE REVIEW

**Comment by colorful-tones** [comment]
I love the buttons to preview the changes. That helps so much. 👏

I’m curious to hear more about the “Community Space”. Is there discussion already around where and what this might look like? 🤔

Would it be a WP.org forum? A developer.wordpress.org area? Or something else?

**Comment by ironnysh** [comment]
Hey @adamziel, thanks for the ping!

Gonna take a deeper look later today—I got a few suggestions :-)

**Comment by adamziel** [comment]
A lot of good feedback and suggestions were incorporated in this PR, I'll go ahead and merge. Thank you SO MUCH @ironnysh @bph ❤️ !

**Comment by adamziel** [comment]
> I’m curious to hear more about the “Community Space”. Is there discussion already around where and what this might look like? 🤔
> Would it be a WP.org forum? A developer.wordpress.org area? Or something else?

@colorful-tones it would be this repository :-) We'd have to transfer it to the WordPress organization first, of course. See the main readme at https://github.com/adamziel/blueprints

**Pull request merged**
